#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# bcsdisplay - convenience shim for `bcs display`
# Passes all arguments to bcs display; defaults via ~/.config/bcs/bcs.conf
set -euo pipefail
shopt -s inherit_errexit
command -v bcs >/dev/null || { >&2 echo "${0##*/}: bcs not found"; exit 18; }
exec bcs display "$@"
#fin
