#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# bcsgenerate - convenience shim for `bcs generate`
# Passes all arguments to bcs generate; defaults via ~/.config/bcs/bcs.conf
set -euo pipefail
exec bcs generate "$@"
#fin
