#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# bcstemplate - convenience shim for `bcs template`
# Passes all arguments to bcs template; defaults via ~/.config/bcs/bcs.conf
set -euo pipefail
shopt -s inherit_errexit
command -v bcs >/dev/null || { >&2 echo "${0##*/}: bcs not found"; exit 18; }
exec bcs template "$@"
#fin
