#!/bin/bash
set -euo pipefail

cd data

declare -a Files=()
declare -- file disp

readarray -t Files < <(find . -type f -name '*.md' ! -path '*README*' |sort)

for file in "${Files[@]}"; do
  cat "$file"
  echo
  disp=${file/.\//}
  disp=${disp/.md/}
#  echo "Ref: [$disp]($file)"
  echo "Ref: [$disp]()"
  echo '---'
  echo
done

#fin
