#!/bin/bash

# Function to strip comments and blank lines
# Works both as a pipe and with string arguments
remblanks() {
  if (($#)); then
    # Arguments provided - process as string
    echo "$*" | grep -v '^[[:blank:]]*#\|^[[:blank:]]*$'
  else
    # No arguments - read from stdin (pipe mode)
    grep -v '^[[:blank:]]*#\|^[[:blank:]]*$'
  fi
}
# Export function for use in subshells
declare -fx remblanks

# If script is executed directly (not sourced), run the function
[[ "${BASH_SOURCE[0]}" != "$0" ]] || remblanks "$@"

#fin
