name: Sync Fork with Upstream

  on:
    schedule:
      - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight UTC
    workflow_dispatch:      # Allow manual trigger

  jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
        - name: Sync fork with upstream
          uses: tgymnich/fork-sync@v2.0.1
          with:
            owner: OkusiAssociates
            base: main
            head: main
            token: ${{ secrets.GITHUB_TOKEN }}

